[package]
name    = "asl-phoenix-console"
version = "2.0.0"
edition = "2021"
authors = ["Edison Lepiten <aieonyx.eu@gmail.com>"]
license = "Apache-2.0"
build   = "build.rs"

[[bin]]
name = "asl-phoenix-console"
path = "src/main.rs"

[profile.release]
panic     = "abort"
opt-level = "s"
lto       = true

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(kani)'] }
