[workspace]
resolver = "2"
members = [
    "asl-common",
    "asl-genesis",
    "asl-arpi",
    "asl-datatier",
    "asl-trustgraph",
    "asl-inverted-admin",
    "asl-axon-bridge",
    "asl-gpu-cap",
    "asl-power-mgmt",
    "asl-network-routing",
    "asl-firewall-cap",
    "asl-touch-sensor",
    "asl-soma",
    "asl-microkit",
    "asl-kani",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Edison Lepiten <aieonyx.eu@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/aieonyx/asl"

# seL4 bindings wired in ASL-M2 once kernel is built
# [workspace.dependencies]
# sel4 = { git = "https://github.com/seL4/rust-sel4" }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = false

[profile.dev]
panic = "abort"
