# Copyright (c) 2026 Edison Lepiten / AIEONYX
# SPDX-License-Identifier: Apache-2.0

[target.aarch64-unknown-none]
linker = "aarch64-linux-gnu-gcc"
rustflags = [
    "-C", "link-arg=-nostartfiles",
]

[target.x86_64-unknown-linux-gnu]
rustflags = []
