[target.aarch64-unknown-none]
rustflags = [
    "-C", "link-arg=-T/home/edisonbl/asl/microkit.ld",
    "-C", "link-arg=--undefined=microkit_name",
    "-C", "link-arg=--undefined=__sel4_ipc_buffer_obj",
    "-C", "link-arg=--undefined=microkit_passive",
    "-C", "link-arg=--undefined=init",
    "-C", "link-arg=--undefined=notified",
]
