[target.aarch64-unknown-none]
rustflags = [
    "-C", "link-arg=-T/home/edisonbl/microkit-sdk-1.4.1/board/qemu_virt_aarch64/release/lib/microkit.ld",
    "-C", "link-arg=-L/home/edisonbl/microkit-sdk-1.4.1/board/qemu_virt_aarch64/release/lib",
    "-C", "link-arg=-lmicrokit",
]
